name: Certora

on: [push, pull_request]

jobs:
  certora:
    name: Certora
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
          java-package: jre

      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install solc-select
        run: pip3 install solc-select

      - name: Solc Select 0.5.12
        run: solc-select install 0.5.12

      - name: Solc Select 0.8.14
        run: solc-select install 0.8.14

      - name: Install Certora
        run: pip3 install certora-cli-alpha-master

      - name: Certora Hub admin & getters
        run: make certora-hub short=1 rule="rely rely_revert deny deny_revert file_ilk_uint256 file_ilk_uint256_revert file_ilk_address file_ilk_address_revert ilk_getters"
        env:
          CERTORAKEY: ${{ secrets.CERTORAKEY }}

      - name: Certora Hub exit, cage, cull, uncull and their reverts
        run: make certora-hub short=1 rule="exit exit_revert cage cage_revert cull cull_revert uncull uncull_revert"
        env:
          CERTORAKEY: ${{ secrets.CERTORAKEY }}

      - name: Certora Hub exec non revert
        run: make certora-hub short=1 rule="exec_normal exec_ilk_culled exec_vat_caged"
        env:
          CERTORAKEY: ${{ secrets.CERTORAKEY }}

      - name: Certora Hub exec ilk culled and vat caged revert
        run: make certora-hub short=1 rule="exec_ilk_culled_revert exec_vat_caged_revert"
        env:
          CERTORAKEY: ${{ secrets.CERTORAKEY }}

      - name: Certora Hub double exec
        run: make certora-hub short=1 rule="exec_exec"
        env:
          CERTORAKEY: ${{ secrets.CERTORAKEY }}
