on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Define Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Foundry
        run: forge install

      - name: Run tests
        run: forge test -v --force --fork-url ${{ secrets.ETH_RPC_URL }}
